version: '3'

vars:
  root_dir:
    sh: pwd
  watch_dir: '{{.root_dir}}/src'
  watch_name: pugbuild

tasks:

  help: task --list-all
  default:
    - task: help

  clean: rm -rf ./build
  build:
    deps:
      - clean
    cmds:
      - deno run -A ./script/build.js
      - deno run -A ./script/bundle.js
      # - mkdir -p ./build/assets
      # - deno bundle ./src/index.js
      #     ./build/assets/index.bundle.js
  serve:
    deps:
      - build
    cmds:
      - deno run -A ./script/serve.js

  watch-def: watchman watch {{.watch_dir}}
  watch-list: watchman watch-list
  # '{{.root_dir}}/src/**/*.pug'
  watch-trigger-def:
    watchman
      -- trigger {{.watch_dir}}
          {{.watch_name}}
          '**/*.pug'
      -- {{.root_dir}}/script/watchbuild.sh
  watch-trigger-list:
    watchman
      trigger-list
      {{.watch_dir}}
  watch-trigger-del:
    watchman
      trigger-del
      {{.watch_dir}} pugbuild
  watch-clean:
    - watchman watch-del-all
    - watchman shutdown-server

  watch:
    cmds:
      - mkdir -p /usr/local/var/run/watchman/root-state
      - task: watch-clean
      - task: watch-def
      - task: watch-list
      - task: watch-trigger-def
      - task: watch-trigger-list

  caddy:
    - cp -R ./build/assets ./build/static
    - cd ./build
      ; caddy file-server --listen 0.0.0.0:8000

  serve-w:
    deps:
      - serve
      - watch
