version: '3'

tasks:

  help: task --list-all
  default:
    - task: help

  build:
    - grain compile ./fib.gr

  grainrun:
    - grain run fib.gr.wasm

  noderun:
    - node ./index.js

  denorun:
    - deno run -A ./deno.js
        {}
        ./fib.gr.wasm
