version: '3'

vars:
  container_name: vite
  image_name: node:20-bullseye-slim

tasks:

  help: task --list-all
  default:
    - task: help

  build: docker build -t {{.image_name}} .
  push: docker push {{.image_name}}

  dev:
    - docker run -ti --rm
        --name {{.container_name}}
        -v $(pwd):/app
        -p 3000:3000
        {{.image_name}}
          bash
