version: '3'

vars:
  container_name: nim-demo
  image_name: mooxe/nim

tasks:

  help: task --list-all
  default:
    - task: help

  dev:
    - podman pull {{.image_name}}
    - podman run -ti --rm
        -v $(pwd):/app
        --name {{.container_name}}
        {{.image_name}}
        /bin/bash

  clean: rm -rf ./build

  nimc:
    deps:
      - clean
    cmds:
      - nim
        --nimcache:$(pwd)/build
        --gen_script
        c ./src/fib.nim
    # --compile_only
    # --cpu:amd64

  emcc:
    deps:
      - nimc
    cmds:
      - cd build
        ; C_INCLUDE_PATH=/usr/share/nim/lib/
          emcc ./@mfib.nim.c
