version: '3'

vars:
  container_name: debuno
  image_name: mooxe/{{.container_name}}

tasks:

  help: task --list-all
  default:
    - task: help

  dev:
    # - podman pull {{.image_name}}
    # - podman run -ti --rm
    - docker pull {{.image_name}}
    - docker run -ti --rm
        -v $(pwd):/app
        -e container_proxy=$container_proxy
        -p 8080:8080
        --name {{.container_name}}
        {{.image_name}}
        /bin/bash
