version: '3'

vars:
  container_name: nimw4
  image_name: mooxe/{{.container_name}}

tasks:

  help: task --list-all
  default:
    - task: help

  dev:
    - podman pull {{.image_name}}
    - podman run -ti --rm
        -p 4444:4444
        -v $(pwd):/app
        --name {{.container_name}}
        {{.image_name}}
        /bin/bash
