version: '3'

tasks:

  help: task --list-all
  default:
    - task: help

  build:
    - zig build-lib
        index.zig
        -target wasm32-freestanding
        -dynamic
        -rdynamic

  # cp -R assets static
  # caddy file-server --listen 0.0.0.0:8000
