version: '3'

tasks:

  help: task --list-all
  default:
    - task: help

  build:
    - zig build-lib
        math.zig
        -target wasm32-freestanding
        -dynamic
        -rdynamic

  run:
    deps:
      - build
    cmds:
      - deno run -A ./index.js
