version: '3'

tasks:

  help: task --list-all
  default:
    - task: help

  build:
    - ldc2 -betterC
      -mtriple=wasm32-unknown-unknown-wasm
      -L-allow-undefined
      wasm.d

  run: deno run -A ./index.js
